services:
  mock: # mock weaviate server for contextionary
    image: wiremock/wiremock:latest
    ports:
      - 8080:8080
    volumes:
      - "./config/wiremock/:/home/wiremock/mappings"
  t2v-contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://mock:8080
    ports:
      - 9999:9999
    depends_on:
      - mock
  search:
    image: opensearchproject/opensearch:2.5.0
    ports:
      - 9200:9200
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # no demo config
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - t2v-contextionary
      - search