<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.ExtensionInput</code>
 */
class ExtensionInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     */
    protected $concept = '';
    /**
     * Generated from protobuf field <code>string definition = 2;</code>
     */
    protected $definition = '';
    /**
     * Generated from protobuf field <code>float weight = 3;</code>
     */
    protected $weight = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $concept
     *     @type string $definition
     *     @type float $weight
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     * @return string
     */
    public function getConcept()
    {
        return $this->concept;
    }

    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConcept($var)
    {
        GPBUtil::checkString($var, True);
        $this->concept = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string definition = 2;</code>
     * @return string
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    /**
     * Generated from protobuf field <code>string definition = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkString($var, True);
        $this->definition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 3;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

}

