<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.InputElement</code>
 */
class InputElement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     */
    protected $concept = '';
    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>uint64 occurrence = 3;</code>
     */
    protected $occurrence = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $concept
     *     @type float $weight
     *     @type int|string $occurrence
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     * @return string
     */
    public function getConcept()
    {
        return $this->concept;
    }

    /**
     * Generated from protobuf field <code>string concept = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConcept($var)
    {
        GPBUtil::checkString($var, True);
        $this->concept = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 occurrence = 3;</code>
     * @return int|string
     */
    public function getOccurrence()
    {
        return $this->occurrence;
    }

    /**
     * Generated from protobuf field <code>uint64 occurrence = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOccurrence($var)
    {
        GPBUtil::checkUint64($var);
        $this->occurrence = $var;

        return $this;
    }

}

