<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.MetaOverview</code>
 */
class MetaOverview extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>int64 wordCount = 2;</code>
     */
    protected $wordCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type int|string $wordCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 wordCount = 2;</code>
     * @return int|string
     */
    public function getWordCount()
    {
        return $this->wordCount;
    }

    /**
     * Generated from protobuf field <code>int64 wordCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWordCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->wordCount = $var;

        return $this;
    }

}

