<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.NearestWords</code>
 */
class NearestWords extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string words = 1;</code>
     */
    private $words;
    /**
     * Generated from protobuf field <code>repeated float distances = 2;</code>
     */
    private $distances;
    /**
     * Generated from protobuf field <code>.contextionary.VectorList vectors = 3;</code>
     */
    protected $vectors = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $words
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $distances
     *     @type \Contextionary\VectorList $vectors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string words = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWords()
    {
        return $this->words;
    }

    /**
     * Generated from protobuf field <code>repeated string words = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->words = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float distances = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDistances()
    {
        return $this->distances;
    }

    /**
     * Generated from protobuf field <code>repeated float distances = 2;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDistances($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->distances = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.contextionary.VectorList vectors = 3;</code>
     * @return \Contextionary\VectorList|null
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    public function hasVectors()
    {
        return isset($this->vectors);
    }

    public function clearVectors()
    {
        unset($this->vectors);
    }

    /**
     * Generated from protobuf field <code>.contextionary.VectorList vectors = 3;</code>
     * @param \Contextionary\VectorList $var
     * @return $this
     */
    public function setVectors($var)
    {
        GPBUtil::checkMessage($var, \Contextionary\VectorList::class);
        $this->vectors = $var;

        return $this;
    }

}

