<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.SchemaSearchParams</code>
 */
class SchemaSearchParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.contextionary.SearchType searchType = 1;</code>
     */
    protected $searchType = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .contextionary.Keyword keywords = 3;</code>
     */
    private $keywords;
    /**
     * Generated from protobuf field <code>float certainty = 5;</code>
     */
    protected $certainty = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $searchType
     *     @type string $name
     *     @type array<\Contextionary\Keyword>|\Google\Protobuf\Internal\RepeatedField $keywords
     *     @type float $certainty
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.contextionary.SearchType searchType = 1;</code>
     * @return int
     */
    public function getSearchType()
    {
        return $this->searchType;
    }

    /**
     * Generated from protobuf field <code>.contextionary.SearchType searchType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSearchType($var)
    {
        GPBUtil::checkEnum($var, \Contextionary\SearchType::class);
        $this->searchType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.Keyword keywords = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.Keyword keywords = 3;</code>
     * @param array<\Contextionary\Keyword>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeywords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Contextionary\Keyword::class);
        $this->keywords = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float certainty = 5;</code>
     * @return float
     */
    public function getCertainty()
    {
        return $this->certainty;
    }

    /**
     * Generated from protobuf field <code>float certainty = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCertainty($var)
    {
        GPBUtil::checkFloat($var);
        $this->certainty = $var;

        return $this;
    }

}

