<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use UnexpectedValueException;

/**
 * Protobuf type <code>contextionary.SearchType</code>
 */
class SearchType
{
    /**
     * Generated from protobuf enum <code>CLASS = 0;</code>
     */
    const PBCLASS = 0;
    /**
     * Generated from protobuf enum <code>PROPERTY = 1;</code>
     */
    const PROPERTY = 1;

    private static $valueToName = [
        self::PBCLASS => 'CLASS',
        self::PROPERTY => 'PROPERTY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

