<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.VectorList</code>
 */
class VectorList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .contextionary.Vector vectors = 1;</code>
     */
    private $vectors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Contextionary\Vector>|\Google\Protobuf\Internal\RepeatedField $vectors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.Vector vectors = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.Vector vectors = 1;</code>
     * @param array<\Contextionary\Vector>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVectors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Contextionary\Vector::class);
        $this->vectors = $arr;

        return $this;
    }

}

