<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.Vector</code>
 */
class Vector extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorEntry entries = 1;</code>
     */
    private $entries;
    /**
     * Generated from protobuf field <code>repeated .contextionary.InputElement source = 2;</code>
     */
    private $source;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Contextionary\VectorEntry>|\Google\Protobuf\Internal\RepeatedField $entries
     *     @type array<\Contextionary\InputElement>|\Google\Protobuf\Internal\RepeatedField $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorEntry entries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntries()
    {
        return $this->entries;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorEntry entries = 1;</code>
     * @param array<\Contextionary\VectorEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Contextionary\VectorEntry::class);
        $this->entries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.InputElement source = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.InputElement source = 2;</code>
     * @param array<\Contextionary\InputElement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSource($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Contextionary\InputElement::class);
        $this->source = $arr;

        return $this;
    }

}

