<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.VectorNNParamsList</code>
 */
class VectorNNParamsList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorNNParams Params = 1;</code>
     */
    private $Params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Contextionary\VectorNNParams>|\Google\Protobuf\Internal\RepeatedField $Params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorNNParams Params = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParams()
    {
        return $this->Params;
    }

    /**
     * Generated from protobuf field <code>repeated .contextionary.VectorNNParams Params = 1;</code>
     * @param array<\Contextionary\VectorNNParams>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Contextionary\VectorNNParams::class);
        $this->Params = $arr;

        return $this;
    }

}

