<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/contextionary.proto

namespace Contextionary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>contextionary.WordStopword</code>
 */
class WordStopword extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool stopword = 1;</code>
     */
    protected $stopword = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $stopword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config\Contextionary::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool stopword = 1;</code>
     * @return bool
     */
    public function getStopword()
    {
        return $this->stopword;
    }

    /**
     * Generated from protobuf field <code>bool stopword = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStopword($var)
    {
        GPBUtil::checkBool($var);
        $this->stopword = $var;

        return $this;
    }

}

